server:
  port: 6666

  tomcat:
    max-connections: 8192   #最大连接数
    accept-count: 100  #排队连接数
    max-threads: 800   #最大线程数
    min-spare-threads: 100  #最小空闲线程数

spring:
  application:
    name: service-DataReceive

  redis:
    host: 127.0.0.1
    port: 6380

  datasource:
    url: jdbc:mysql://10.2.4.33:3306/iems_app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: iems.gree
    driver-class-name: com.mysql.jdbc.Driver


#配置服务注册中心信息
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true #是否检索服务
    registry-fetch-interval-seconds: 30 # 间隔多长时间(s)去检索服务注册信息，默认是30s
    service-url:
      defaultZone: http://localhost:8000/eureka  #指定服务注册中心的位置

