server:
  port: 7777

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: service-DataPush
  redis:
    host: 10.2.10.128
    port: 6380
  datasource:
    url: jdbc:mysql://10.2.4.33:3306/iems_app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    #url: jdbc:mysql://localhost:3306/iems_app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

    username: root
    password: iems.gree
    driver-class-name: com.mysql.cj.jdbc.Driver

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url:
#      defaultZone: http://localhost:8000/eureka/


localUrl: http://localhost:8000/
remoteReceiveUrl: http://10.40.255.22:9118/receive

energyName: zongBu
pushLimit: 100

web-socket-endpoints:
  endpoints:
    - "ws://10.40.255.22:9118/ws/data/alarm"
    - "ws://10.40.255.22:9118/ws/data/statistic"
    - "ws://10.40.255.22:9118/ws/data/redis"