server:
  port: 7777

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: service-DataPush
#  redis:
#    host: 116.205.171.117
#    port: 7523
#  datasource:
#    url: jdbc:mysql://116.205.171.117:7522/iems_app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    #url: jdbc:mysql://localhost:3306/iems_app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  redis:
    host: 116.205.171.117
    port: 7513
    timeout: 5000
  datasource:
    url: jdbc:mysql://116.205.171.117:7508/iems_app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: iems.gree
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url:
#      defaultZone: http://localhost:8000/eureka/


localUrl: http://localhost:8000/
remoteReceiveUrl: http://service.iems.gree.com:8092/receive

energyName: sjddev
pushLimit: 100

websocket:
  endpoints:
    - ws://localhost:8092/ws/data/alarm
    - ws://localhost:8092/ws/data/statistic
    - ws://localhost:8092/ws/data/redis