server:
  port: 7777

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: service-DataPush
#  redis:
#    host: 110.41.51.96
#    port: 7523
  redis:
    host: localhost
    port: 6380
  datasource:
    url: jdbc:mysql://110.41.51.96:7522/iems_app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    url: jdbc:mysql://localhost:3306/iems_app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#  redis:
#    host: 116.205.171.117
#    port: 7513
#  datasource:
#    url: jdbc:mysql://116.205.171.117:7508/iems_app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: iems.gree
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url:
#      defaultZone: http://localhost:8000/eureka/


localUrl: http://localhost:8000/
remoteReceiveUrl: http://service.iems.gree.com:8092/receive

energyName: shequ
pushLimit: 100


websocket:
  endpoints:
    - ws://service.iems.gree.com:8092/ws/data/alarm
    - ws://service.iems.gree.com:8092/ws/data/statistic
    - ws://service.iems.gree.com:8092/ws/data/redis
  # 线程池配置
  thread-pool-size: 5
  batch-size: 200
  batch-timeout: 5

  # 队列监控阈值
  queue-alert-threshold: 10000
  queue-cleanup-threshold: 50000